require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - ".simplecov"
    - "spec/tmp/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/RakeEnvironment:
  Enabled: false

RSpec/ImplicitExpect:
  EnforcedStyle: should

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "spec/dummy/db/migrate/**/*"

Rails/DynamicFindBy:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Rails/I18nLocaleAssignment:
  Enabled: false
